spring:
  application.name: student

  datasource:
    url: jdbc:mysql://localhost:3306/mypass_student
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type:
          preferred_uuid_jdbc_type: CHAR


